# Generated by Django 4.2.14 on 2024-07-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('ploughing', 'Ploughing'), ('sowing', 'Sowing'), ('watering', 'Watering'), ('harvesting', 'Harvesting')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.workerdetails')),
                ('equipment_needed', models.ManyToManyField(related_name='assignments', to='dashboard.equipmentdetails')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.AlterField(
            model_name='cropdetails',
            name='task_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.assignmentdetails'),
        ),
        migrations.DeleteModel(
            name='TaskDetails',
        ),
    ]
