# Generated by Django 4.2.14 on 2024-07-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_assignmentdetails_alter_cropdetails_task_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentdetails',
            name='equipment_needed',
        ),
        migrations.AddField(
            model_name='assignmentdetails',
            name='equipment_needed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.equipmentdetails'),
        ),
    ]
